# Generated by Django 5.0.6 on 2024-06-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True, unique=True),
        ),
    ]
