# Generated by Django 5.0.6 on 2024-06-01 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_venteproduct_delete_ventestock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_total', models.DecimalField(decimal_places=0, max_digits=10)),
                ('prix_restant', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='ajoutstock',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='ajoutstock',
            name='reste',
        ),
        migrations.AddField(
            model_name='ajoutstock',
            name='facture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='stock.facture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venteproduct',
            name='facture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='stock.facture'),
            preserve_default=False,
        ),
    ]
