# Generated by Django 5.0.6 on 2024-07-10 14:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_facture_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trosa',
            old_name='somme',
            new_name='montant',
        ),
        migrations.RemoveField(
            model_name='trosa',
            name='fournisseur',
        ),
        migrations.AddField(
            model_name='trosa',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trosa',
            name='montant_restant',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trosa',
            name='owner',
            field=models.CharField(default='john', max_length=25),
            preserve_default=False,
        ),
    ]
