# Generated by Django 5.0.6 on 2025-03-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0015_alter_marque_nom"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="qte_uniter",
            new_name="qte_detail",
        ),
        migrations.RemoveField(
            model_name="ajoutstock",
            name="qte_uniter_transaction",
        ),
        migrations.RemoveField(
            model_name="product",
            name="prix_uniter",
        ),
        migrations.RemoveField(
            model_name="venteproduct",
            name="qte_uniter_transaction",
        ),
        migrations.AddField(
            model_name="ajoutstock",
            name="qte_detail_transaction",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="ajoutstock",
            name="qte_unit_transaction",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="detail",
            name="qte_max_unit",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="prix_detail",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="prix_unit",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="qte_unit",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="venteproduct",
            name="qte_detail_transaction",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="venteproduct",
            name="qte_unit_transaction",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
