# Generated by Django 5.0.6 on 2025-04-03 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0016_rename_qte_uniter_product_qte_detail_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="ajout_stock",
        ),
        migrations.AddField(
            model_name="ajoutstock",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_related",
                to="stock.product",
            ),
        ),
    ]
