# Generated by Django 5.0.6 on 2025-04-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_alter_ajoutstock_product_reglement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reglement',
            name='note',
        ),
    ]
