# Generated by Django 5.0.6 on 2025-04-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_remove_reglement_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajoutstock',
            name='prix_detail',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ajoutstock',
            name='prix_gros',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ajoutstock',
            name='prix_unit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
