# Generated by Django 5.0.6 on 2025-04-28 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_ajoutstock_prix_detail_ajoutstock_prix_gros_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='venteproduct',
            name='facture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='stock.facture'),
        ),
        migrations.CreateModel(
            name='FilAttenteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('prix_total', models.DecimalField(decimal_places=0, max_digits=10)),
                ('prix_restant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('client', models.CharField(blank=True, default='', max_length=20)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='venteproduct',
            name='fil_attente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_related', to='stock.filattenteproduct'),
        ),
    ]
