# Generated by Django 5.0.6 on 2024-06-20 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_remove_ajoutstock_facture_alter_facture_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('somme', models.DecimalField(decimal_places=0, max_digits=10)),
                ('fournisseur', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='stock.fournisseur')),
            ],
        ),
    ]
