# Generated by Django 5.0.6 on 2024-06-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_trosa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajoutstock',
            name='prix_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venteproduct',
            name='prix_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
