# Generated by Django 5.0.6 on 2024-07-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_ajoutstock_prix_total_venteproduct_prix_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
