# Generated by Django 5.0.6 on 2024-07-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_remove_venteproduct_vendeur_facture_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='trosa',
            name='adress',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trosa',
            name='contact',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
